services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: crudGO
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db/script.sql:/docker-entrypoint-initdb.d/script.sql

  app:
    build: .
    container_name: go-crud-app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: crudGO
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: on-failure

volumes:
  db-data:
